### ISSUE TITLE
deeplabv3plus: pth——>onnx——>ncnn

### ISSUE THREAD

**Issue by xiaoloudexiaofang** [runrunrun1994/ncnn-android-deeplabv3plus#4]
How do I implement the conversion of pth to onnx and then to ncnn?
Can you share the code for this?

**Comment by runrunrun1994** [comment]
You can see this link [https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx](https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx)
